#!/usr/bin/env bash
# Configure my domain zone:
# www --> 914-lb-01 52.86.226.192
# web-01 --> 914-web-01 100.25.111.115
# web-02 --> 914-web-02 3.90.80.81

# -- To be evaluated --
# domain_information () {
#     line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#     echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
# }

# if [ "$#" == 1 ]
# then
#   domain_information "$1" "www"
#   domain_information "$1" "lb-01"
#   domain_information "$1" "web-01"
#   domain_information "$1" "web-02"
# elif [ "$#" == 2 ]
# then
#   domain_information "$1" "$2"
# fi
#-- To be evaluated --

print_domain_subdomain () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
